ci:
  autoupdate_commit_msg: "ci: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            \.cspell\.json
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.12.0
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.1
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.2
    hooks:
      - id: nbqa-black
      - id: nbqa-flake8
      - id: nbqa-isort
      - id: nbqa-pyupgrade
        args:
          - --py36-plus

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - >
            cell.metadata.code_folding
            cell.metadata.id
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
