ci:
  autoupdate_commit_msg: "MAINT: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly
  skip:
    - prettier
    - taplo

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.id
            cell.metadata.pycharm
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/ComPWA/policy
    rev: 0.3.9
    hooks:
      - id: check-dev-files
        args:
          - --no-cspell-update
          - --no-github-actions
          - --no-gitpod
          - --no-prettierrc
          - --no-pypi
          - --no-python
          - --no-ruff
          - --no-version-branches
          - --repo-name=ComPWA-demo
          - --repo-title="ComPWA demos"
      - id: colab-toc-visible

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-flake8
      - id: nbqa-isort
      - id: nbqa-pyupgrade
        args:
          - --py36-plus

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            \.cspell\.json
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: v0.8.1
    hooks:
      - id: taplo

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args:
          - --in-place

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black-jupyter

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.9.0
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
