# Defines the bare requirements for setting up Binder
name: compwa-demo
channels:
  - defaults
dependencies:
  - python==3.8.*
  - pip>=19
  - graphviz # for binder
  - pip:
      - ipywidgets
      - matplotlib
