name: CD

on:
  release:
    types:
      - prereleased
      - released

jobs:
  milestone:
    if: startsWith(github.ref, 'refs/tags')
    uses: ComPWA/actions/.github/workflows/close-milestone.yml@v1
