name: Notebook

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ipynb"

jobs:
  pytest:
    name: Run all notebooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: hynek/setup-cached-uv@v2
      - name: Install dependencies
        run: |
          sudo apt-get -y install graphviz
          pip install uv
      - run: |
          for notebook in $(git ls-files | grep ipynb); do
            uv pip sync requirements.txt --quiet --system
            pytest $notebook --no-header --no-summary
          done
