name: Notebook

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ipynb"

jobs:
  pytest:
    name: Run all notebooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@master
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          sudo apt-get -y install graphviz
          pip install tensorflow==2.7 typing-extensions~=3.7.4 wrapt~=1.12.1
          pip install ipywidgets matplotlib nbmake pytest
      - run: pytest --nbmake
