name: Notebook

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.ipynb"

jobs:
  pytest:
    name: Run all notebooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Install graphviz
        run: sudo apt-get -y install graphviz
      - run: |
          for notebook in $(git ls-files | grep ipynb); do
            uv sync --extra dev --quiet
            source .venv/bin/activate
            pytest $notebook --no-header
          done
